#!/bin/bash
HADOOP_CONF_PATH=$ds_path/init/hadoop_conf
function error() {
  echo "Error, $1" >> $ds_path/log/ds_install.log && exit 1
}

function warn() {
  echo "Warn, $1" >> $ds_path/log/ds_install.log
}

function info() {
  echo "Info, $1" >> $ds_path/log/ds_install.log
}

if [ -f $HADOOP_CONF_PATH/suc ]; then
  exit 0
fi

if [ -z $HDFS_HA_ENABLE ] || [ "$HDFS_HA_ENABLE" == 'false' ]; then
  warn "HA is not enabled."
  if [ -z $HADOOP_NN_HOST ]; then
    error "Error, HADOOP_NN_HOST is mandatory if HA is not enabled."
  fi
  sed -i "s/Put site-specific property overrides in this file./Generated by Big data platform, DO NOT modify by hand./" $HADOOP_CONF_PATH/core-site.xml
  sed -i "/^<configuration>/a\  <property>\n    <name>fs.defaultFS</name>\n    <value>hdfs\://${HADOOP_NN_HOST}\:8020</value>\n  </property>" $HADOOP_CONF_PATH/core-site.xml

elif [ "$HDFS_HA_ENABLE" == 'true' ]; then
  info "HA is enabled."
  [ -z $NAMESERVICES ] && NAMESERVICES=cluster
  if [ -z $HADOOP_NN_HOSTS ]; then
    error "In HA mode, we must know the two NameNode hosts for configuration."
  fi
  NAMENODE_A=$(echo $HADOOP_NN_HOSTS | awk -F , '{print $1}')
  NAMENODE_B=$(echo $HADOOP_NN_HOSTS | awk -F , '{print $2}')

  if [ -z $HADOOP_JOURNAL_URI ]; then
    # Format: qjournal://jn1:8485;jn2:8485;jn3:8485
    error "Journal URI is mandatory if HA is enabled."
  fi

  if [ -z $HADOOP_ZK_URI ]; then
    # Format: zk1:2181,zk2:2181,zk3:2181
    error "HADOOP_ZK_URI is mandatory if HA is enabled."
  fi
  sed -i "s/Put site-specific property overrides in this file./Generated by Big data platform, DO NOT modify by hand./" $HADOOP_CONF_PATH/core-site.xml
  sed -i "/^<configuration>/a\  <property>\n    <name>fs.defaultFS</name>\n    <value>hdfs\://${NAMESERVICES}</value>\n  </property>\n  <property>\n    <name>ha.zookeeper.quorum</name>\n   <value>${HADOOP_ZK_URI}</value>\n  </property>" $HADOOP_CONF_PATH/core-site.xml
  sed -i "/^<configuration>/a\  <property>\n    <name>dfs.nameservices</name>\n    <value>${NAMESERVICES}</value>\n  </property>\n  <property>\n    <name>dfs.ha.namenodes.${NAMESERVICES}</name>\n    <value>nn1,nn2</value>\n  </property>\n  <property>\n    <name>dfs.namenode.rpc-address.${NAMESERVICES}.nn1</name>\n    <value>${NAMENODE_A}:8020</value>\n  </property>\n  <property>\n    <name>dfs.namenode.rpc-address.${NAMESERVICES}.nn2</name>\n    <value>${NAMENODE_B}:8020</value>\n  </property>\n  <property>\n    <name>dfs.namenode.shared.edits.dir</name>\n    <value>${HADOOP_JOURNAL_URI}/${NAMESERVICES}</value>\n  </property>\n  <property>\n    <name>dfs.ha.automatic-failover.enabled</name>\n    <value>true</value>\n  </property>\n  <property>\n    <name>dfs.ha.fencing.methods</name>\n    <value>shell(/bin/true)</value>\n  </property>\n  <property>\n    <name>dfs.client.failover.proxy.provider.${NAMESERVICES}</name>\n    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>\n  </property>\n  <property>\n    <name>dfs.journalnode.edits.dir</name>\n    <value>/var/data/hadoop/journal/</value>\n  </property>" $HADOOP_CONF_PATH/hdfs-site.xml
else
  error "Only true and false are accepted for HDFS_HA_ENABLE"
fi

if [ -z $YARN_HA_ENABLE ] || [ "$YARN_HA_ENABLE" == 'false' ]; then
  warn "Yarn HA is not enable."
  if [ -z $HADOOP_RM_HOST ]; then
#    HADOOP_RM_HOST=$(hostname)
    error "We must know the Resourcemanager host for configuration."
  fi
  sed -i "/^<configuration>/a\  <property>\n    <name>yarn.resourcemanager.hostname</name>\n    <value>${HADOOP_RM_HOST}</value>\n  </property>" $HADOOP_CONF_PATH/yarn-site.xml;

elif [ "$YARN_HA_ENABLE" = 'true' ]; then
  info "Yarn HA is enable."
  if [ -z $HADOOP_RM_HOSTS ]; then
    error "In HA mode, we must know the two Resourcemanager hosts for configuration."
  fi
  RESOURCEMANAGER_A=$(echo $HADOOP_RM_HOSTS | awk -F , '{print $1}')
  RESOURCEMANAGER_B=$(echo $HADOOP_RM_HOSTS | awk -F , '{print $2}')
  sed -i "/^<configuration>/a\  <property>\n  <name>yarn.resourcemanager.ha.enabled</name>\n  <value>true</value>\n  </property>\n <property>\n    <name>yarn.resourcemanager.cluster-id</name>\n    <value>cluster1</value>\n  </property>\n  <property>\n  <name>yarn.resourcemanager.ha.rm-ids</name>\n  <value>rm1,rm2</value>\n  </property>\n  <property>\n  <name>yarn.resourcemanager.hostname.rm1</name>\n  <value>${RESOURCEMANAGER_A}</value>\n  </property>\n   <property>\n   <name>yarn.resourcemanager.hostname.rm2</name>\n   <value>${RESOURCEMANAGER_B}</value>\n  </property>\n  <property>\n   <name>yarn.resourcemanager.webapp.address.rm1</name>\n   <value>${RESOURCEMANAGER_A}:8088</value>\n  </property>\n  <property>\n  <name>yarn.resourcemanager.webapp.address.rm2</name>\n  <value>${RESOURCEMANAGER_B}:8088</value>\n  </property>\n  <property>\n   <name>yarn.resourcemanager.zk-address</name>\n  <value>${HADOOP_ZK_URI}</value>\n  </property>" $HADOOP_CONF_PATH/yarn-site.xml
else
  error "Only true and false are accepted for YARN_HA_ENABLE"
fi

touch $HADOOP_CONF_PATH/suc
